services:
  cpu:
    profiles: [cpu]
    build:
      context: .
      dockerfile: Dockerfile.cpu
    image: humanoid-ros:cpu
    network_mode: host
    stdin_open: true
    tty: true
    command: sleep infinity
    volumes:
      - .:/ws

  gpu:
    profiles: [gpu]
    build:
      context: .
      dockerfile: Dockerfile.gpu
    image: humanoid-ros:gpu
    network_mode: host
    devices:
      - nvidia.com/gpu=all
    stdin_open: true
    tty: true
    command: sleep infinity
    volumes:
      - .:/ws
